from pathlib import Path

import pytest

from app.dxcc.adif import parse_adif, qso_summary
from app.dxcc.cty import CtyDatabase
from app.dxcc.tracker import NeededTracker

BUNDLED = Path(__file__).resolve().parent.parent / "app" / "bundled" / "cty_builtin.dat"

ADIF = """
Generated by test
<adif_ver:5>3.1.4
<eoh>
<call:6>JA1NUT <band:3>20m <mode:2>CW <qso_date:8>20260101 <eor>
<call:6>JA1NUT <band:3>40m <mode:3>FT8 <eor>
<call:5>G4IRN <band:3>20m <mode:3>SSB <qsl_rcvd:1>Y <eor>
<call:6>HB9CVQ <band:3>20m <mode:4>MFSK <submode:3>FT4 <eor>
"""


def test_parse_adif():
    qsos = parse_adif(ADIF)
    assert len(qsos) == 4
    call, band, mode, confirmed = qso_summary(qsos[0])
    assert (call, band, mode, confirmed) == ("JA1NUT", "20m", "CW", False)
    assert qso_summary(qsos[2])[3] is True
    assert qso_summary(qsos[3])[2] == "FT4"


@pytest.fixture()
def tracker(tmp_path) -> NeededTracker:
    db = CtyDatabase.from_file(BUNDLED)
    t = NeededTracker(db, tmp_path / "worked.json")
    t.import_adif(ADIF)
    return t


def test_needed_levels(tracker):
    # Never worked Bouvet at all
    assert tracker.needed("3Y0K", "20m", "CW") == "atno"
    # Japan worked on 20m CW and 40m FT8
    assert tracker.needed("JA9XX", "20m", "CW") == ""
    assert tracker.needed("JA9XX", "15m", "CW") == "band"
    assert tracker.needed("JA9XX", "20m", "FT8") == "mode"
    assert tracker.needed("JA9XX", "40m", "FT8") == ""


def test_qso_updates_needed(tracker):
    assert tracker.needed("3Y0K", "20m", "CW") == "atno"
    tracker.record_qso("3Y0K", "20m", "CW")
    assert tracker.needed("3Y0K", "20m", "CW") == ""
    assert tracker.needed("3Y0K", "17m", "CW") == "band"


def test_persistence(tracker, tmp_path):
    db = CtyDatabase.from_file(BUNDLED)
    t2 = NeededTracker(db, tmp_path / "worked.json")
    assert t2.needed("JA1AA", "20m", "CW") == ""


def test_import_stats(tmp_path):
    db = CtyDatabase.from_file(BUNDLED)
    t = NeededTracker(db, tmp_path / "w.json")
    result = t.import_adif(ADIF)
    assert result["qsos"] == 4
    assert result["entities"] == 3  # Japan, England, Switzerland


def test_confirmed_tracking_and_no_downgrade(tracker):
    # G4IRN had qsl_rcvd=Y -> confirmed SSB slot
    assert tracker.slot_status("England", "20m", "SSB") == "C"
    assert tracker.slot_status("Japan", "20m", "CW") == "W"
    # re-import without confirmation must not downgrade C -> W
    tracker.import_adif("<eoh><call:5>G4IRN <band:3>20m <mode:3>SSB <eor>")
    assert tracker.slot_status("England", "20m", "SSB") == "C"
    # confirmation upgrades W -> C
    tracker.import_adif("<eoh><call:6>JA1NUT <band:3>20m <mode:2>CW <qsl_rcvd:1>Y <eor>")
    assert tracker.slot_status("Japan", "20m", "CW") == "C"


def test_legacy_v1_file_migrates(tmp_path):
    import json
    path = tmp_path / "worked.json"
    path.write_text(json.dumps({"Japan": {"20m": ["CW", "FT8"]}}))
    db = CtyDatabase.from_file(BUNDLED)
    t = NeededTracker(db, path)
    assert t.slot_status("Japan", "20m", "CW") == "W"
    assert t.needed("JA1NUT", "20m", "CW") == ""
    assert t.needed("JA1NUT", "20m", "FT4") == "mode"


def test_entity_matrix_and_stats(tracker):
    m = tracker.entity_matrix("Japan", ["20m", "40m"], ["CW", "FT8"])
    assert m["20m"]["CW"] == "W"
    assert m["40m"]["FT8"] == "W"
    assert m["20m"]["FT8"] == ""
    st = tracker.stats()
    assert st["entities_worked"] == 3
    assert st["confirmed_slots"] == 1
